### ISSUE TITLE
A user should be able to set default values through a config file

### ISSUE THREAD

**Issue by scopeta** [scopeta/focusedme#5]
### Description

A user should be able to set default values through a config.file

Currently, the default values are set to common Pomodoro configuration (25,5,25 mins) and the user can change that behavior through command line arguments

**Comment by Arthurcn96** [comment]
Hello There! 

I was thinking about solving this issue and I was wondering:
 -  Is it okay to create a 'fm.ini' as the config file?
 - Which command do you have in mind to save the values in the config file?

**Comment by scopeta** [comment]
Hey Arthur,
I was thinking about removing the following lines that set default values from the main .py file and move them to a fm.ini. 

NUM_ROUNDS = 3
LENGHT_ARGS = {"focus_time": 25, "short_break": 5, "long_break": 25}

Those are classic values for Pomodoro timers, but someone may want their default values increased to 30/ 45 mins focused sessions, or enjoy a 10 mins break ;)

What do you think about having another argument option (e.g. -s) that save the lastest values passed in the command line? 

Thanks!
Fabio
